apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-log-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/hands-on-k8s/logging